# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: brysah
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          extras_css: |
              .track .name { max-width: 200px !important; }
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_pagespeed: no
          plugin_pagespeed_detailed: no
          plugin_pagespeed_url: .user.website
          plugin_contributors: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_limit: 6
          plugin_music_playlist: https://open.spotify.com/embed/playlist/37i9dQZF1DWZ8wKkpiPwjx?utm_source=generator
